---
- name: Check if "sponge" is installed and in PATH
  command: which sponge
  changed_when: false
  ignore_errors: true
  register: prometheus_sponge_installed

- name: Set "sponge" installed fact
  set_fact:
    prometheus_sponge_is_installed: |-
        {% if prometheus_sponge_installed is defined and "rc" in prometheus_sponge_installed and prometheus_sponge_installed.rc == 0 -%}
        {{ true }}{% else -%}{{ false }}{% endif -%}
