---
- name: Create {{ ansible_service_mgr }} configuration file for {{ prometheus_software_service_name }} service
  become: true
  template:
    dest: '/etc/init.d/{{ prometheus_software_service_name }}'
    src: 'templates/daemon-{{ ansible_service_mgr }}.j2'
    owner: root
    group: root
    mode: 0750
  notify:
    - Restart Prometheus service
