---
- name: Check pacman core index present
  stat:
    path: /var/lib/pacman/sync/core.db
  changed_when: false
  register: pacman_core_index

- name: Run the equivalent of 'pacman -Sy'
  become: true
  pacman:
    update_cache: true
  # pacman cache is older than 3 days
  register: prometheus_pacman_update
  retries: 5
  delay: 10
  until: prometheus_pacman_update is succeeded
  when:
    - not pacman_core_index.stat.exists or
      60*60*24*3 < (ansible_date_time.epoch | int - pacman_core_index.stat.mtime | int)
