---
- name: Check apk index present
  find:
    paths: /var/cache/apk
    file_type: file
    patterns: '*.tar.gz'
  register: apk_indexes

- name: Run the equivalent of 'apk update'
  become: true
  apk:
    update_cache: true
  register: prometheus_apk_update
  retries: 5
  delay: 10
  until: prometheus_apk_update is succeeded
  when: apk_indexes.matched | int == 0
