---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting aerospike_exporter (alicebob) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_allow_build_test: true
    prometheus_software_author: alicebob
    prometheus_software_binary_name: asprom
    prometheus_software_name: aerospike_exporter_alicebob
    prometheus_software_description: 'Prometheus aerospike_exporter (alicebob), exporter for various Aerospike metrics'
    prometheus_software_documentation: 'https://github.com/alicebob/asprom'

- name: Set {{ prometheus_software_name }} architecture facts
  set_fact:
    prometheus_software_architecture: '{{ prometheus_architecture | replace("-", "_") }}'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--listen={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/\
      {{ prometheus_software_version }}/{{ prometheus_software_binary_name }}_\
      {{ prometheus_software_version | regex_replace('^(v)?') }}_{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
