---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting grok_exporter (fstab) install
  set_fact:
    prometheus_exporter: true
    prometheus_grok_exporter_fstab_patterns_directory: '{{ prometheus_grok_exporter_fstab_patterns_dir | default(prometheus_etc_dir + "/grok_patterns") }}'
    prometheus_grok_exporter_fstab_sync_patterns_directory: true
    prometheus_software_author: fstab
    prometheus_software_binary_name: grok_exporter
    # Do not perform tests, tests only succeed where IPv6 is available
    prometheus_software_name: grok_exporter_fstab
    prometheus_software_description: 'Prometheus grok_exporter, export from arbitrary unstructured log data'
    prometheus_software_documentation: 'https://github.com/fstab/grok_exporter'
    prometheus_software_use_prerelease: true

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_opts:
      - '-config {{ prometheus_etc_dir }}/grok_exporter_fstab.yml'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/\
      {{ prometheus_software_version }}/{{ prometheus_software_binary_name }}-\
      {{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.zip"
      # Source builds are unrealistic unless we build Oniguruma libraries too...

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Setup {{ prometheus_software_name_version }} configuration file'
  become: true
  copy:
    content: '{{ prometheus_grok_exporter_fstab_cfg | default(lookup("file", "../files/grok_exporter_fstab.yml")) }}'
    dest: '{{ prometheus_etc_dir }}/grok_exporter_fstab.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: 0640
    backup: true
  notify:
    - Restart Prometheus service

- name: Find the {{ prometheus_software_binary_name }} binary
  find:
    paths: '{{ prometheus_software_install_dir }}'
    patterns: '{{ prometheus_software_binary_name }}'
    file_type: file
    recurse: true
  register: prometheus_binary_file_location

- name: Include task to move {{ prometheus_software_name_version }} files down one directory
  include_tasks: _move_files_down_one_directory.yml
  when:
    - prometheus_binary_file_location.files
    - prometheus_binary_file_location.files[0].path != prometheus_software_install_dir + '/' + prometheus_software_binary_name

- name: Synchronize the {{ prometheus_software_name_version }} example grok patterns to {{ prometheus_grok_exporter_fstab_patterns_directory }}
  include_tasks: _copy_remote_directory_contents.yml
  vars:
    prometheus_copy_dest_dir: '{{ prometheus_grok_exporter_fstab_patterns_directory }}'
    prometheus_copy_src_dir: '{{ prometheus_software_install_dir }}/patterns'
    prometheus_copy_dir_mode: '0755'
    prometheus_copy_file_mode: '0644'
  when: prometheus_grok_exporter_fstab_sync_patterns_directory | bool

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
