---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting iperf3_exporter (edgard) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: edgard
    prometheus_software_binary_name: iperf3_exporter
    prometheus_software_name: iperf3_exporter_edgard
    prometheus_software_description: 'Prometheus iperf3_exporter (edgard), iPerf3 probing of endpoints'
    prometheus_software_documentation: 'https://github.com/edgard/iperf3_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
