---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting process_exporter (ncabatoff) install
  set_fact:
    prometheus_exporter: true
    # 0.7.0 and 0.7.1 don't include precompiled binaries
    prometheus_software_allow_build_test: true
    prometheus_software_author: ncabatoff
    prometheus_software_binary_name: process-exporter
    prometheus_software_name: process_exporter_ncabatoff
    prometheus_software_description: 'Prometheus process_exporter (ncabatoff), mines /proc to report on selected processes'
    prometheus_software_documentation: 'https://github.com/ncabatoff/process-exporter'
    # Defined by prometheus_process_exporter_ncabatoff_cfgs:
    prometheus_software_opts: []

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/{{ prometheus_software_version }}\
      {{ prometheus_software_binary_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include tasks to perform individual {{ prometheus_software_name_version }} configurations
  include_tasks: _install_instance.yml
  loop_control:
    loop_var: installer_instance
  loop: '{{ prometheus_process_exporter_ncabatoff_cfgs }}'

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
