---
# Installs promcron script for monitoring cron job success and last run time

- name: Include task to install and locate sponge
  include_tasks: _install_sponge.yml

- name: Install promcron script to {{ prometheus_script_directory }}/promcron
  become: true
  template:
    dest: '{{ prometheus_script_directory }}/promcron'
    src: templates/promcron.sh.j2
    owner: root
    group: root
    mode: 0555
  vars:
    prometheus_promcron_ansible_managed: true

- name: Symlink {{ prometheus_script_directory }}/promcron to {{ prometheus_script_promcron_link_dir }}/promcron
  become: true
  file:
    src: '{{ prometheus_script_directory }}/promcron'
    dest: '{{ prometheus_script_promcron_link_dir }}/promcron'
    owner: root
    group: root
    state: link
    force: true
