---
# handlers file for mesaguy.prometheus

- name: Force systemd to reread configs
  become: true
  systemd:
    daemon_reload: true

- name: Restart Prometheus service
  become: true
  service:
    name: '{{ prometheus_software_service_name }}'
    enabled: true
    state: restarted

- name: Reload Prometheus service
  become: true
  service:
    name: '{{ prometheus_software_service_name }}'
    state: reloaded
