---
defaults:
  port: 9113
  tgroup: nginx
software:
  name: nginxinc/nginx-prometheus-exporter
  release: v0.8.0
  prerelease: null
  url: https://github.com/nginxinc/nginx-prometheus-exporter
  source: https://github.com/nginxinc/nginx-prometheus-exporter.git
  updated: '2021-02-18T00:45:22.477297'
  master:
    commit:
      sha: dc47bd007c85fd6e2fa3d91f6e376edf2d32c598
      timestamp: '2021-02-08T16:53:11'
    files: []
  releases:
    - name: v0.6.0
      commit: null
      timestamp: '2020-02-19T18:10:03'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.6.0-linux-amd64.tar.gz
          commit: null
          size: 5903721
          sha256: sha256:2e8f1038ca8aa5b215ee04379df3f13eb242be5e1721e615ac679381011b06e9
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.6.0/nginx-prometheus-exporter-0.6.0-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.6.0-linux-i386.tar.gz
          commit: null
          size: 5748646
          sha256: sha256:27acf66333b0fd8a2d5f68de2cc221e26d3dd30e50d8cca886f586c49f15ca1c
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.6.0/nginx-prometheus-exporter-0.6.0-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:104fec117c99d5c50dff4025a286d29326f89c22d0987da3112ed9d3af378757
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.6.0/sha256sums.txt
    - name: v0.5.0
      commit: null
      timestamp: '2019-12-06T20:26:29'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.5.0-linux-amd64.tar.gz
          commit: null
          size: 5722310
          sha256: sha256:42e049d2313ef341f02eea72271d4342ca330a89f68150905c78324052b4b42d
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.5.0/nginx-prometheus-exporter-0.5.0-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.5.0-linux-i386.tar.gz
          commit: null
          size: 5576505
          sha256: sha256:b516826c2cc6f4eb485d2aec247c8699d8005cf0d0484282f87b0fa24c88de13
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.5.0/nginx-prometheus-exporter-0.5.0-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:52a218236bb721a4f15aef832172336bc9b657d1e9ff2d0849543d317eb6f625
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.5.0/sha256sums.txt
    - name: v0.4.2
      commit: null
      timestamp: '2019-07-22T15:24:09'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.4.2-linux-amd64.tar.gz
          commit: null
          size: 5724796
          sha256: sha256:8b3d234844826364615e72ca187844aaecefb6cb639fee2af8b465d95f380fc7
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.2/nginx-prometheus-exporter-0.4.2-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.4.2-linux-i386.tar.gz
          commit: null
          size: 5577210
          sha256: sha256:8d1cef3bfe41e376b6dee60617865c70ed022b7010c95fccf916f00508940e98
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.2/nginx-prometheus-exporter-0.4.2-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:787cc86934bbd314789d090a2a383c09c8059819ef73bd2a5b7c36034dc8b861
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.2/sha256sums.txt
    - name: v0.4.1
      commit: null
      timestamp: '2019-06-12T10:46:45'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.4.1-linux-amd64.tar.gz
          commit: null
          size: 5724040
          sha256: sha256:fded95b7a511fbd0ddff8c600aa8776d936d0c7ac1a9fdfa5666c3952e926656
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.1/nginx-prometheus-exporter-0.4.1-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.4.1-linux-i386.tar.gz
          commit: null
          size: 5577146
          sha256: sha256:25f43c346fef37bd8eeeb0e105dd9b4ecc3c435f88b17c311ca9ed7ab244aa82
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.1/nginx-prometheus-exporter-0.4.1-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:138c887b65c7fa7ed4b15c493819e449bb426fa355890954e19e35f5bee0566a
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.1/sha256sums.txt
    - name: v0.4.0
      commit: null
      timestamp: '2019-05-30T11:30:28'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.4.0-linux-amd64.tar.gz
          commit: null
          size: 5724221
          sha256: sha256:f5fdcac170b69c43b4e82bf47dd021bc9db219a87818667253c893e0e657321b
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.0/nginx-prometheus-exporter-0.4.0-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.4.0-linux-i386.tar.gz
          commit: null
          size: 5576616
          sha256: sha256:f7e5cac0d3c0cdc138e006be195a3ddcdd2f370661192d6a2b6437a6499fc4de
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.0/nginx-prometheus-exporter-0.4.0-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:97b0c4a1c3c630e0e7aac4d61fa653ccd1d0f29c102d746f0f5a8a792a798156
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.0/sha256sums.txt
    - name: v0.3.0
      commit: null
      timestamp: '2019-02-07T12:19:48'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
          commit: null
          size: 5034515
          sha256: sha256:31de68284339041fc5539f3b5431276989bea3de3705d932e80cc9f89cc9b21a
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.3.0-linux-i386.tar.gz
          commit: null
          size: 4885982
          sha256: sha256:55843ddccfce20a31cbee945dbb00174bfca112d0e53b50ac9a6ab688a248f0f
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:7ab204cf9788cdb6d811810e37691500bc20e6f56f56b38f02e4c7ff9addd1aa
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/sha256sums.txt
    - name: v0.2.0
      commit: null
      timestamp: '2018-11-13T12:55:52'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.2.0-linux-amd64.tar.gz
          commit: null
          size: 5028720
          sha256: sha256:2b6ee8173613386213537f1f3d8289d8daaa9c23fa040b6e6becdd476536743e
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.2.0/nginx-prometheus-exporter-0.2.0-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.2.0-linux-i386.tar.gz
          commit: null
          size: 4879087
          sha256: sha256:e06b5bc5c0bbc777eb541a5ec3e20ca26d022a3aac56867aab4b2ee15bc6faf0
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.2.0/nginx-prometheus-exporter-0.2.0-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:589128493bbc5f1d385ec54ec023543f896cf4ed5e6d7958294047c301fa785e
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.2.0/sha256sums.txt
    - name: v0.1.0
      commit: null
      timestamp: '2018-10-04T12:42:20'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.1.0-linux-amd64.tar.gz
          commit: null
          size: 2966944
          sha256: sha256:77e1a51dce50e685e8ff86835a566da37cfcc22064816b89227ce3a01b21944b
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.1.0/nginx-prometheus-exporter-0.1.0-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.1.0-linux-i386.tar.gz
          commit: null
          size: 2852401
          sha256: sha256:b14848f8f5602c5e4873d095485586ff7a76c3c37f6fd73a00db3fdda9e82b5c
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.1.0/nginx-prometheus-exporter-0.1.0-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:de76a3a08a39d9d8708dc4f5ddebfc673135a2d87c0cd5affae315bdbc334a9a
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.1.0/sha256sums.txt
    - name: v0.7.0
      commit: null
      timestamp: '2020-04-23T17:10:50'
      prerelease: false
      files:
        - name: nginx-prometheus-exporter-0.7.0-linux-amd64.tar.gz
          commit: null
          size: 5872225
          sha256: sha256:08a0a054aecedec4aa2772569325a346403d2c1fba6f88739553416c2f4f77e6
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.7.0/nginx-prometheus-exporter-0.7.0-linux-amd64.tar.gz
        - name: nginx-prometheus-exporter-0.7.0-linux-i386.tar.gz
          commit: null
          size: 5734205
          sha256: sha256:7643f8b60f267920ac9299d107d31f30252dda8a461d02d79395d69f2d01bfc6
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.7.0/nginx-prometheus-exporter-0.7.0-linux-i386.tar.gz
        - name: sha256sums.txt
          commit: null
          size: 233
          sha256: sha256:c068bba09862cbe415e0be55431579792192ed17ace3d998a377a2cc1051ef84
          url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.7.0/sha256sums.txt
    - name: v0.8.0
      commit:
        sha: de15093f96d81efa71e7eaa3a007d28183ac5e14
        timestamp: '2020-06-17T18:37:51'
      timestamp: '2020-06-17T18:39:17'
      prerelease: false
      files: []
