---
defaults:
  port: 9445
  tgroup: nvidia
software:
  name: mindprince/nvidia_gpu_prometheus_exporter
  release: null
  prerelease: null
  url: https://github.com/mindprince/nvidia_gpu_prometheus_exporter
  source: https://github.com/mindprince/nvidia_gpu_prometheus_exporter.git
  updated: '2020-03-05T01:43:00.406982'
  master:
    commit:
      sha: 0d52cd2f711ea00601b711d8127b8634b2844150
      timestamp: '2018-10-27T22:40:57'
    files: []
  releases: []
